const LoginConst = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGIN_CREDENTIALS_ERROR: "LOGIN_CREDENTIALS_ERROR",
  LOGIN_FORBIDDEN_ERROR: "LOGIN_FORBIDDEN_ERROR",
  LOGIN_USER_NOT_FOUND_ERROR: "LOGIN_USER_NOT_FOUND_ERROR",
  LOGIN_NOT_HANDLED_ERROR: "LOGIN_NOT_HANDLED_ERROR"
};
export default LoginConst;
