const UserManagmentConst = {
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  USER_DATA: "USER_DATA",
  CLOSE_UPDATE: "CLOSE_UPDATE",
  CLOSE_MODAL: "CLOSE_MODAL",
  RESPONSE_MESSAGE: "RESPONSE_MESSAGE",
  ADMINS_COUNT: "ADMINS_COUNT"
};
export default UserManagmentConst;
